version: '3'
volumes:
  elasticsearch_persistent:
services:
  elasticsearch:
    image: activecm-beaker/elasticsearch:${ELK_VERSION_TAG:-latest}
    build: ./elasticsearch
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${ELASTIC_HTTP_PORT:-9200}:9200"
    volumes:
      - elasticsearch_persistent:/usr/share/elasticsearch/data

  kibana:
    image: activecm-beaker/kibana:${ELK_VERSION_TAG:-latest}
    build: ./kibana
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${KIBANA_HTTP_PORT:-5601}:5601"
    depends_on:
      - elasticsearch